audit_header: false
title: Charleston's Best Real Estate Training
description: Brendon Payne, a top Real Estate Agent in Charleston, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: /events/
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/

client:
  name: Brendon Payne
  title:
  license_number:
  about_markdown: |
    Brendon is originally from Central Illinois, just outside of Chicago.  After Graduating College, Brendon worked his way up the Management Ranks within the Loss Prevention and Safety Departments of 2 Global retailers.  In 2005 Brendon moved forward with his plan to help Sellers make the best decisions regarding what is typically one of their largest investments.  In a very short period of time he became one of the top producing agents on the Grand Strand, and is currently selling over 100 properties per year and is ranked in the top 1% of agents Nationwide and in the Top 50 Century 21 Agents in America.

     Because of a very diverse business background he is able to quickly analyze a client's goals and help them establish a timeline and strategies that will help them accomplish the financial goals they have set for themselves.  In his own words he says: "To me, it's more important to figure out what the client is trying to accomplish, big picture, and then determine whether buying or selling will help them get there. Too many agents focus on themselves and getting the commission check.  Somewhere in those situations, the client and their needs get left behind.  Bottom line: My goal is to provide Facts, Strategies, and Results and get the client where they want to be.
  market: Charleston
  brand: The Brendon Payne Team
  brokerage: Century 21
  address:  4999 Carolina Forest Blvd, Ste 18<br>Myrtle
  phone: 843-903-3550
  phone_type:
  phone2:
  phone2_type:
  email: bpaynesells@yahoo.com
  url: http://www.brendonpayne.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Charleston Real Estate Podcast with Brendon Payne'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Charleston Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Brendon Payne Team - your professional Charleston Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Charleston, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Brendon Payne'

images:
  client_headshot_path: /img/headshot.JPG
  hero_logo_path: /img/logo.png
  hero_logo_path2: /img/logo2.png
  hero_logo_path3: /img/logo3.png
  logo_width_number: 50
  hero_text: Charleston Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#008dcc'
  theme_color: '#6e7e88'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
