audit_header: false
title: Myrtle Beach's Best Real Estate Training
description: -- CLIENT NAME --, a top Real Estate Agent in -- MARKET --, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/


client:
  name: Greg Harrelson
  title:
  license_number:
  about_markdown: |
    I have been in the real estate business for over 20 years. I have been professionally trained by coaches like Mike, Matthew, Tom Ferry, Chet Holmes and Tony Robbins. I have experience in the area of general, commercial and real estate development. My goal is to empower my clients with the information necessary to make sound financial decisions while being sensitive to the experience one is looking for in real estate ownership. 
  market: Myrtle Beach
  brand: The Harrelson Group
  brokerage: Century 21
  address: 4999 Carolina Forest Blvd, Ste. 18<br>Myrtle Beach, SC 29579
  phone: 843-903-3550
  phone_type: Office
  phone2: 843-457-7816
  phone2_type: Cell
  email: gregharrelson@gmail.com
  url: http://www.c21TheHarrelsonGroup.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/myrtlebeachrealestatesales
  linkedin_url: https://www.linkedin.com/in/gregharrelson/
  gplus_url:
  youtube_url: https://www.youtube.com/c/c21theharrelsongroup
  twitter_url: https://twitter.com/Gregharrelson
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.JPG
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#BDAE85'
  theme_color: '#404042'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
